import './globals.css'
import { Inter } from 'next/font/google'

// Metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
